localhost:
  port: 2000
web:
  upload-path: data
spring:
    jpa:
    show-sql: true
server:
  port: 1111

udp:
  server:
    host: 127.0.0.1
    port: 8008
logging:
    config: classpath:logback-spring.xml


